### ISSUE TITLE
Cacoo: Can not retrieve diagram data by API.

### ISSUE THREAD

**Issue by luozengbin** [kiwanami/emacs-cacoo#1]
windows+cygwin環境でCacooを入れてみました。Public画像の表示は問題なく出来ましたが。
しかし、Private画像の表示がNGでいた。
## Cacooモード起動際に次ぎのようにエラーポーイのメッセージが出ています。

Cacoo: Progress  0/0  ...
Cacoo: Progress  1/0  ...
Cacoo: Progress  1/1  [complete]
## Cacoo: Can not retrieve diagram data by API. -> Process [wget] exited abnormally : 

回避策を教えて頂けませんでしょうか？

**Comment by kiwanami** [comment]
いくつか原因が考えられます。

まず、private 画像を取得するには apikey が必要です。
Cacoo にWebでログインして設定ページにAPIキーというページがありますので、そこで秘密の文字列を取得します。
秘密の文字列を以下のように設定します。
(setq cacoo:api-key "APIKEY")

apikeyの問題でなければ wget や emacs との間の連携の問題が考えられますので、 emacs のバージョン（取得した場所とか）やwgetのバージョンを教えていただいてよろしいでしょうか。

**Comment by luozengbin** [comment]
apikeyの問題ではなさそうです。
emacs のバージョンは”GNU Emacs 23.3.1 (i386-mingw-nt5.1.2600) of 2011-03-10 on 3249CTO”です。
取得先は”http://ftp.gnu.org/pub/gnu/emacs/windows/”です。
wgetのバージョンはGNU Wget 1.12です。

**Comment by kiwanami** [comment]
う〜ん。バージョンなども問題なさそうな気がします。

プライベート画像は cacoo:anything-command (C-c , I) で入れていますか？
画像のURLが https://cacoo.com/api/v1/diagrams... というものになっていないと取って来れません。
いかがでしょうか？

**Comment by luozengbin** [comment]
cacoo:anything-commandを実行するとミニバッファーに"Now retrieving diagram data. Wait a moment..."が表示されて、
その後は無反応です。
プライベート画像のURLがhttps://cacoo.com/api/v1/diagrams... ではなく、 https://cacoo.com/diagrams... となっていた。

**Comment by kiwanami** [comment]
cacoo:anything-command は裏でCacooAPIから画像の一覧を取りに行きますので、しばらく待つと画像の一覧が表示されるようになっています。手元では画像150枚くらいの一覧が数秒で終わっていますので、何十秒も返事がない場合はちょっとおかしいかもしれません。

とりあえずの回避策では、プライベート画像のURLに /api/v1/ を追加してもらっても良いでしょうか。もしそれで取得できていれば、あとは cacoo:anything-command の問題を解決すれば大丈夫そうです。

URLを変えてもダメな場合は、やっぱりAPIkeyに問題がある可能性があります。あと、 (setq cacoo:debug t) の設定を追加して実行すると _cacoo:debug_ バッファにログが残ります。可能であればこのログを送ってもらえるとより正確に状況把握ができます。（もしデバッグ設定してもログが出ない場合は、cacoo.elを一旦Emacsで開いて、 M-x eval-current-buffer すると出るはずです。）

お手数おかけしますがよろしくお願いします。

**Comment by luozengbin** [comment]
kiwanamiさん

親切なご回答、ありがとうございました。

<b>プライベート画像の表示について</b>
プライベート画像のURLに /api/v1/ を追加したら、表示が出来ました！

<b>cacoo:anything-commandについて</b>
cacoo:anything-command はNGのままでした。
cacoo:anything-commandを実行すると
_cacoo:debug_ バッファーに"AT: startup"メッセージが出力されている。
ミニバッファーに"Now retrieving diagram data. Wait a moment..."が表示される。
その後は無反応です。
wiresharkで通信状況を確認したところ、通信が発生していないです。

もう一回cacoo:anything-commandを実行すると
_cacoo:debug_ バッファーに"cacoo:anything locked."メッセージが出力されている。

<b>_cacoo:debug_ バッファー詳細</b>

1 >> cacoo:display-diagram : https://cacoo.com/api/v1/diagrams/H4cIjBzFW1C4PAfB-B0F88.png / 450
2 DF RSZ / (get-first (("https://cacoo.com/api/v1/diagrams/H4cIjBzFW1C4PAfB-B0F88.png" . 450)))
3 >> cacoo:resize-diagram : https://cacoo.com/api/v1/diagrams/H4cIjBzFW1C4PAfB-B0F88.png / 450
4 DF RSZ / (get-waiting (("https://cacoo.com/api/v1/diagrams/H4cIjBzFW1C4PAfB-B0F88.png" . 450)))
5 DF ORG / (get-first ("https://cacoo.com/api/v1/diagrams/H4cIjBzFW1C4PAfB-B0F88.png"))
6 >> cacoo:load-diagram-remote : https://cacoo.com/api/v1/diagrams/H4cIjBzFW1C4PAfB-B0F88.png
7 >>   found cache file : d:/ProgramData/emacs/junk/.cimg/H4cIjBzFW1C4PAfB-B0F88.png
8 DF ORG / (get-waiting ("https://cacoo.com/api/v1/diagrams/H4cIjBzFW1C4PAfB-B0F88.png"))
9 DF ORG / (set ("https://cacoo.com/api/v1/diagrams/H4cIjBzFW1C4PAfB-B0F88.png"))
10 >>   get : "d:/ProgramData/emacs/junk/.cimg/H4cIjBzFW1C4PAfB-B0F88.png"
11 >> cacoo:resize-diagram-convert : https://cacoo.com/api/v1/diagrams/H4cIjBzFW1C4PAfB-B0F88.png / 450
12 >>   found cache file : d:/ProgramData/emacs/junk/.cimg/resize_450_H4cIjBzFW1C4PAfB-B0F88.png
13 DF RSZ / (set (("https://cacoo.com/api/v1/diagrams/H4cIjBzFW1C4PAfB-B0F88.png" . 450)))
14 >>   get(display) : "d:/ProgramData/emacs/junk/.cimg/resize_450_H4cIjBzFW1C4PAfB-B0F88.png"
15 >> cacoo:display-diagram-by-image : d:/ProgramData/emacs/junk/.cimg/resize_450_H4cIjBzFW1C4PAfB-B0F88.png <- https://cacoo.com/api/v1/diagrams/H4cIjBzFW1C4PAfB-B0F88.png / 450
初回cacoo:anything-command実行時のログ
16 AT: startup
２回目以降cacoo:anything-command実行時のログ
17 cacoo:anything locked.

※一応プライベート画像の表示が出来たので、このIssueをクローズしてもいいです。

長くなりました、よろしくお願いします。

**Comment by kiwanami** [comment]
ログありがとうございます。とりあえず画像が読み込めて良かったです。
プライベート画像が取得できると言うことはAPIkeyは正しいです。

Emacs内部のエラーではなくて、wgetが終了してしまうのはもしかしたらオプションが何か間違っているのかもしれません。もし余裕がありましたら、APIkeyを埋め込んで以下のコマンドをcygwinから実行してもらっても良いでしょうか。

wget -q -O - 'https://cacoo.com/api/v1/diagrams.json?apiKey=*APIKEY*'

期待通りに動けば、標準出力にJSONで画像の一覧が出力されます。

**Comment by luozengbin** [comment]
アドバイス、ありがとうございました。

やはり、wgetのオプション問題です。

私の環境では↓
×　wget -q -O - 'https://cacoo.com/api/v1/diagrams.json?apiKey=*APIKEY*'
◯　wget -q --no-check-certificate　-O - 'https://cacoo.com/api/v1/diagrams.json?apiKey=*APIKEY*'

一応cacoo.elの205行を次のように修正して回避しています。
(defvar cacoo:http-get-stdout-cmd '("wget" "-q" "--no-check-certificate" "-O" "-" url))

改めて、感謝します！ ;-)

**Comment by kiwanami** [comment]
実は以前はそのオプションをつけていたのですが、最近 --no-check-certificate 無しでもうごくようになったと聞いていたので一旦消していました。
あとでドキュメントに注意書きしようと思います。

ご協力ありがとうございました。また何かありましたらお気軽にどうぞ。

**Comment by luozengbin** [comment]
なるほど、了解しました。
今後もよろしくお願いします。
